const CAPTIONS = {
	0:  "Kangchendzonga National Park, Sikkim, India",
	1:  "Half Dome from Glacier Point, Yosemite National Park, California",
	2:  "Blue Lake, Inyo National Forest, California",
	3:  "Lakes Trail, Kings Canyon National Park, California",
	4:  "Horsetooth Mountain, Fort Collins, Colorado",
	5:  "Dolores Park, San Francisco, California",
	6:  "Embaracadero, San Francisco, California",
	7:  "Perugia, Cambria, Italy",
	8:  "Alghero, Sardinia, Italy",
	9:  "Rifugio Menaggio, Lake Como, Italy",
	10: "Puez-Geisler National Park, South Tyrol, Italy",
	11: "Peak of Monte Grona, Lake Como, Italy",
	12: "Puez-Geisler National Park, South Tyrol, Italy",
	13: "Vembanad Lake, Cochin, Kerala, India",
	14: "Angel Island State Park, San Francisco, California",
	15: "Soberanes Point, Carmel, Monterey, California",
	16: "West Point Lighthouse, Discovery Park, Seattle, Washington",
	17: "Wallace Falls State Park, Snohomish County, Washington",
	18: "Laguna Creek Beach, Santa Cruz, California",
	19: "Tent Rocks National Monument, Sandoval County, New Mexico",
	20: "Gennargentu National Park, Cala Ganone, Sardinia, Italy",
	21: "McLaren Park, San Francisco, California",
	22: "Angel Island State Park, San Francisco Bay, California",
	23: "Prewitt Ridge, Big Sur, California",
	24: "Yosemite Falls trail, Yosemite National Park, California",
	25: "Kangchendzonga National Park, Sikkim, India",
	26: "Briones Regional Park, Lafayette, California",
	27: "Mendocino Headlands State Park, Mendocino, California",
	28: "Four Mile Trail, Yosemite National Park, California",
	29: "Shilshole Bay, Ballard, Seattle, Washington"
};