const PHOTOS = {
	0:  { caption: "Kangchendzonga National Park, Sikkim, India", dominantColor: "#89979A" },
	1:  { caption: "Half Dome from Glacier Point, Yosemite National Park, California", dominantColor: "#6D86B8" },
	2:  { caption: "Blue Lake, Inyo National Forest, California", dominantColor: "#82B0D8" },
	3:  { caption: "Lakes Trail, Kings Canyon National Park, California", dominantColor: "#B36F3C" },
	4:  { caption: "Horsetooth Mountain, Fort Collins, Colorado", dominantColor: "#2F343B" },
	5:  { caption: "Dolores Park, Mission, San Francisco, California", dominantColor: "#B8C9CC" },
	6:  { caption: "Kaibab National Forest, Grand Canyon, Arizona", dominantColor: "#8B6151" },
	7:  { caption: "Perugia, Cambria, Italy", dominantColor: "#6C7971" },
	8:  { caption: "Alghero, Sardinia, Italy", dominantColor: "#B26542" },
	9:  { caption: "Rifugio Menaggio, Lake Como, Italy", dominantColor: "#5E6C3C" },
	10: { caption: "Puez-Geisler National Park, South Tyrol, Italy", dominantColor: "#5575C0" },
	11: { caption: "Peak of Monte Grona, Lake Como, Italy", dominantColor: "#486BA1" },
	12: { caption: "Puez-Geisler National Park, South Tyrol, Italy", dominantColor: "#7082A2" },
	13: { caption: "Vembanad Lake, Cochin, Kerala, India", dominantColor: "#ADB9D1" },
	14: { caption: "Angel Island State Park, San Francisco Bay, California", dominantColor: "#6A723E" },
	15: { caption: "Soberanes Point, Carmel, Monterey, California", dominantColor: "#8A7C4C" },
	16: { caption: "West Point Lighthouse, Discovery Park, Seattle, Washington", dominantColor: "#EC965C" },
	17: { caption: "Wallace Falls State Park, Snohomish County, Washington", dominantColor: "#D6D3CE" },
	18: { caption: "Laguna Creek Beach, Santa Cruz, California", dominantColor: "#9C7E52" },
	19: { caption: "Tent Rocks National Monument, Sandoval County, New Mexico", dominantColor: "#CBAC86" },
	20: { caption: "Gennargentu National Park, Cala Ganone, Sardinia, Italy", dominantColor: "#454934" },
	21: { caption: "McLaren Park, San Francisco, California", dominantColor: "#94ABBD" },
	22: { caption: "Angel Island State Park, San Francisco Bay, California", dominantColor: "#2F3411" },
	23: { caption: "Prewitt Ridge, Big Sur, California", dominantColor: "#A73E28" },
	24: { caption: "Yosemite Falls Trail, Yosemite National Park, California", dominantColor: "#536C8B" },
	25: { caption: "Kangchendzonga National Park, Sikkim, India", dominantColor: "#808B63" },
	26: { caption: "Briones Regional Park, Lafayette, California", dominantColor: "#546420" },
	27: { caption: "Mendocino Headlands State Park, Mendocino, California", dominantColor: "#D8DEE0" },
	28: { caption: "Four Mile Trail, Yosemite National Park, California", dominantColor: "#709BC3" },
	29: { caption: "Shilshole Bay, Ballard, Seattle, Washington", dominantColor: "#E9906E" },
};