const PHOTOS = [
	{index: 0, bg: "#89979A", caption: "Kangchendzonga National Park, Sikkim, India"},
	{index: 1, bg: "#6D86B8", caption: "Half Dome from Glacier Point, Yosemite National Park, California"},
	{index: 2, bg: "#82B0D8", caption: "Blue Lake, Inyo National Forest, California"},
	{index: 3, bg: "#B36F3C", caption: "Lakes Trail, Kings Canyon National Park, California"},
	{index: 4, bg: "#2F343B", caption: "Horsetooth Mountain, Fort Collins, Colorado"},
	{index: 5, bg: "#B8C9CC", caption: "Dolores Park, Mission, San Francisco, California"},
	{index: 6, bg: "#8B6151", caption: "Kaibab National Forest, Grand Canyon, Arizona"},
	{index: 7, bg: "#6C7971", caption: "Perugia, Cambria, Italy"},
	{index: 8, bg: "#B26542", caption: "Alghero, Sardinia, Italy"},
	{index: 9, bg: "#5E6C3C", caption: "Rifugio Menaggio, Lake Como, Italy"},
	{index: 10, bg: "#5575C0", caption: "Puez-Geisler National Park, South Tyrol, Italy"},
	{index: 11, bg: "#486BA1", caption: "Peak of Monte Grona, Lake Como, Italy"},
	{index: 12, bg: "#7082A2", caption: "Puez-Geisler National Park, South Tyrol, Italy"},
	{index: 13, bg: "#ADB9D1", caption: "Vembanad Lake, Cochin, Kerala, India"},
	{index: 14, bg: "#6A723E", caption: "Angel Island State Park, San Francisco Bay, California"},
	{index: 15, bg: "#8A7C4C", caption: "Soberanes Point, Carmel, Monterey, California"},
	{index: 16, bg: "#EC965C", caption: "West Point Lighthouse, Discovery Park, Seattle, Washington"},
	{index: 17, bg: "#D6D3CE", caption: "Wallace Falls State Park, Snohomish County, Washington"},
	{index: 18, bg: "#9C7E52", caption: "Laguna Creek Beach, Santa Cruz, California"},
	{index: 19, bg: "#CBAC86", caption: "Tent Rocks National Monument, Sandoval County, New Mexico"},
	{index: 20, bg: "#454934", caption: "Gennargentu National Park, Cala Ganone, Sardinia, Italy"},
	{index: 21, bg: "#94ABBD", caption: "McLaren Park, San Francisco, California"},
	{index: 22, bg: "#2F3411", caption: "Angel Island State Park, San Francisco Bay, California"},
	{index: 23, bg: "#A73E28", caption: "Prewitt Ridge, Big Sur, California"},
	{index: 24, bg: "#536C8B", caption: "Yosemite Falls Trail, Yosemite National Park, California"},
	{index: 25, bg: "#808B63", caption: "Kangchendzonga National Park, Sikkim, India"},
	{index: 26, bg: "#546420", caption: "Briones Regional Park, Lafayette, California"},
	{index: 27, bg: "#D8DEE0", caption: "Mendocino Headlands State Park, Mendocino, California"},
	{index: 28, bg: "#709BC3", caption: "Four Mile Trail, Yosemite National Park, California"},
	{index: 29, bg: "#E9906E", caption: "Shilshole Bay, Ballard, Seattle, Washington"}
];